appconfig:
  name: "fiber-boilerplate"
  host: "0.0.0.0"
  port: "9999"
  secret: "myVeryStrongSecretPassword64bitLength"

database:
  driver: "postgres"
  host: "localhost"
  port: "5432"
  username: "postgres"
  password: "postgres"
  ssl: "disable"
  database: "boilerplate"

log:
  host: "localhost"
  port: "9200"
  index: "ms-briapi-spot-dashboard"
  user: "elastic"
  pass: "P@ssw0rd"

errorcontract:
  json_path_file: "./script/errorContract.json"

